service: aws-lambda-cache

custom:
  parameter_name: /lambda_cache/ssm_parameter

provider:
  name: aws
  runtime: python3.6
  stage: test
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:ssm"
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - "parameter${self:custom.parameter_name}"

package:
 include:
   - ../aws_lambda_cache/**
 exclude:
   - ../aws_lambda_cache/__pycache__/**

functions:
  test_ssm:
    handler: test_ssm.single_parameter
  test_ssm_2:
    handler: test_ssm.double_parameter

resources:
  Resources:
    SsmParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Description: Normal Parameter for testing
        Name: /lambda_cache/ssm_parameter
        Tier: Standard
        Type: String
        Value: "Dummy Value 1"
    SsmParameter2:
      Type: AWS::SSM::Parameter
      Properties:
        Description: Normal Parameter for testing
        Name: /lambda_cache/ssm_parameter_2
        Tier: Standard
        Type: String
        Value: "Dummy Value 2"

