service: aws-lambda-cache

custom:
  parameter_name: /lambda_cache/something
  parameter_name_2 : /lambda_cache/test/something_else

provider:
  name: aws
  runtime: python3.6
  stage: test
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:ssm"
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - "parameter${self:custom.parameter_name}"
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:ssm"
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - "parameter${self:custom.parameter_name_2}"

package:
 include:
   - ../aws_lambda_cache/**
 exclude:
   - ../aws_lambda_cache/__pycache__/**

functions:
  single_handler:
    handler: test_ssm.single_parameter
  double_handler:
    handler: test_ssm.double_parameter
  default_param:
    handler: test_ssm.rename_param

