name: Deploy and Test

# Triggers
on:
  push:
    branches:
      - '*'

# Specify what jobs to run
jobs:
  sls_deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v1 

      # Install npm and it's dependencies
      - name: Install npm dependencies
        working-directory: ./integration_tests
        run: npm install

      # Install SLS
      - name: Serverless Install
        working-directory: ./integration_test
        run: npm i -g serverless@1.54.0
      
      - name: Serverless Deploy
        working-directory: ./integration_test
        run: serverless deploy

        