name: Release

# Triggers
on:
  release:
    types: [published]

# Specify what jobs to run
jobs:
  Build_Release:
    name: Build_Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      # version 1.2
      - name: Install Poetry
        uses: dschep/install-poetry-action@db2e37f48d1b1cd1491c4590338ebc7699adb425

      # We do not need dependencies for build or publish (native Poetry)
      # - name: Install Dependencies
      #   run: poetry install
      
      - name: Build
        working-directory: .
        run: poetry build
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      
      - name: publish
        working-directory: .
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish

    # Success / Failure, publish to Slack
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@51259479e07a6e3c44b826b39b771be8106142ba
        with:
          channel: lambda-cache
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@51259479e07a6e3c44b826b39b771be8106142ba
        with:
          channel: lambda-cache
          status: FAILED
          color: danger