name: Deploy and Test

# Triggers
on:
  push:
    branches:
      - 'github_actions*'
      - 'version*'
      - 'release'

# Specify what jobs to run
jobs:
  sls_deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.8


      # Install poetry
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py && python get-poetry.py --yes && poetry config virtualenvs.create false

      - name: Setup Poetry
        run: poetry install
      
      - name: Run Test..
        working-directory: ./tests
        run: poetry shell pytest test_ssm_cache.py::parameter_not_exist_var_handler

