name: Test

# Triggers
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'feature'

# Specify what jobs to run
jobs:
  TestBuildDeploy:
    name: UnitTest
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }} 
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Install Dependencies
        run: poetry install

      - name: Test with pytest
        working-directory: ./tests
        run: poetry run pytest test_ssm_cache.py --cov ../aws_lambda_cache --cov-report term-missing -vv
      
      - name: Code Quality
        run: poetry run black simple_lambda_cache --check

      # Only runs on release branch
      - name: Update Test Coverage
        if: github.ref == 'refs/heads/release'  # only on the feature branch do we publish code coverage stats
        working-directory: ./tests
        run: |
          poetry run coveralls debug
          coveralls
      
      - name: Build
        if: github.ref == 'refs/heads/release'
        working-directory: .
        run: poetry build
      
      - name: publish
        if: github.ref == 'refs/heads/release'
        working-directory: .
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish

      - name: Archive production artifacts
        if: github.ref == 'refs/heads/release'
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

